[personal]
    first_name = "Krystof"
    last_name = "Spiller"

    [personal.info]
        homepage = 'krystofs.com'
        linkedin = "krystof-spiller"
        github = "krystofspiller"
        email = "krystof.spiller@gmail.com"
        phone = "+45 91 86 94 01"

[layout]
    accent_color = "#e6805f"

    [layout.fonts]
        regular_font = "Source Sans 3"
        header_font = "Roboto"

[lang]
    header_quote = "Senior Software Engineer | Engineering customer-centric solutions"
    cv_footer = "Curriculum vitae"
    letter_footer = "Cover letter"