#:schema https://raw.githubusercontent.com/mintyfrankie/brilliant-CV/main/metadata.toml.schema.json

# Set the output language
# INFO: value must matches folder suffix; i.e "zh" -> "./modules_zh"
language = "en"

[layout]
    # Optional values: skyblue, red, nephritis, concrete, darknight
    # You can also use a custom color by hex code i.e. "#1E90FF"
    awesome_color = "#0aa2fa"

    # Skips are for controlling the spacing between sections and entries
    before_section_skip = "1pt"
    before_entry_skip = "1pt"
    before_entry_description_skip = "1pt"

    [layout.fonts]
        regular_fonts = ["Source Sans 3"]
        header_font = "Roboto"

    [layout.header]
        # Optional values: left, center, right
        header_align = "left"

        # Decide if you want to display profile photo or not
        display_profile_photo = false

    [layout.entry]
        # Decide if you want to put your company in bold or your position in bold
        display_entry_society_first = true

        # Decide if you want to display organisation logo or not
        display_logo = true

[inject]
    # Decide if you want to inject AI prompt or not
    inject_ai_prompt = false

    # Decide if you want to inject keywords or not
    inject_keywords = false
    injected_keywords_list = []

[personal]
    first_name = "Krystof"
    last_name = "Spiller"

    # The order of this section will affect how the entries are displayed
    # The custom value is for any additional information you want to add, name it as custom-1, custom-2, etc.
    [personal.info]
        github = "Laegas"
        phone = "+45 91 86 94 01"
        email = "krystof.spiller@gmail.com"
        linkedin = "krystof-spiller"
        # homepage = "jd.me.org"
        # [personal.info.custom-1]
        #     # image = "" # Example: image("./path/to/image.png")
        #     awesomeIcon = "graduation-cap" # Example: "graduation-cap" see https://typst.app/universe/package/fontawesome/
        #     text = "PhD"
        #     link = "https://www.example.com"

# add a new section if you want to include the language of your choice
# each section must contains the following fields
[lang.en]
    header_quote = "Senior Fullstack Software Engineer"
    cv_footer = "Curriculum vitae"
    letter_footer = "Cover letter"
